### PR TITLE
New AGPL LICENSE.txt and .travis.yml file; Rebuilt Gemfile.lock file

### PR DESCRIPTION
**Pull request by jasnow**
- Added AGPL LICENSE.txt file
- Added initial .travis.yml file.
- Removed gem numbers in Gemfile
- Rebuilt Gemfile.lock file (lot of gem upgrades).

### CODE REVIEW

**Comment by atticoos** [comment]
:pager: @kyletns or @cmuld3r to review/verify gem changes

**Comment by jasnow** [comment]
Anything else I need to do?

**Comment by jasnow** [comment]
@kyletns or @cmuld3r - Can you please review/verify this PR?

**Comment by jasnow** [comment]
Appears to be no interest so closing PR.

**Comment by atticoos** [comment]
If you can contribute the license file independently of the gem upgrades, I am happy to take a look at a PR containing only that

**Comment by jasnow** [comment]
@ajwhite - Recommend you add the the license file yourself.

**Comment by jasnow** [comment]
Here it the URL over in my repo: https://github.com/jasnow/RideWithBernie/blob/master/LICENSE.txt

**Comment by atticoos** [comment]
:+1:

**Comment by kyleschmolze** [comment]
Hey @jasnow thanks so much for the PR! Sorry to be absent, I've been off the grid for 10 days, and am just seeing this now. The changes look good, can you just explain why you should we should upgrade the versions of these gems? Also, what does "snowify" mean? Other than that, I'm happy to merge.

**Comment by jasnow** [comment]
"snowify" is a set of things I change on all of my repos - use overcommit, use rvm and .rvmrc, use floating gem numbers in Gemfile, check for license, use TravisCI, etc.

"Upgrade the version of these gems" - My view is that is better that using older versions.

**Comment by kyleschmolze** [comment]
Ok great, checking it out now.

**Comment by jasnow** [comment]
Thanks

**Comment by kyleschmolze** [comment]
Looks good!

**Comment by jasnow** [comment]
Thanks

**Pull request merged**
